apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
    role: service
  name: nginxservice
spec:
  ports:
    - port: 8800
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    name: nginx
