apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginxexternal
    role: service
  name: nginxexternal
spec:
  ports:
    - port: 8800
      targetPort: 80
      protocol: TCP
      name: tcp
    - port: 8900
      targetPort: 90
      protocol: UDP
      name: udp
  selector:
    name: nginx
  type: NodePort
