apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: policy2
 namespace: ns1
spec:
 podSelector:
  matchLabels:
    name: apache
 ingress:
  - from:
     - ipBlock:
        cidr: 172.16.1.0/24
        except:
        - 172.16.1.3/32
        - 172.16.1.4/32
     - namespaceSelector:
        matchLabels:
         project: myproject1
     - podSelector:
        matchLabels:
         role: frontend1
    ports:
     - protocol: TCP
       port: 80
     - protocol: UDP
       port: 1234
  - from:
     - namespaceSelector:
        matchLabels:
         project: myproject2
     - podSelector:
        matchLabels:
         role: frontend2
    ports:
     - protocol: TCP
       port: 80
 egress:
  - to:
     - ipBlock:
        cidr: 172.16.2.0/24
        except:
        - 172.16.2.103/32
        - 172.16.2.104/32
     - namespaceSelector:
        matchLabels:
         project: myproject1
     - podSelector:
        matchLabels:
         role: frontend1
    ports:
     - protocol: TCP
       port: 8080
     - protocol: UDP
       port: 4321
