apiVersion: v1
kind: Service
metadata:
  labels:
    name: apacheexternal1
    role: service
  name: apacheexternal1
spec:
  ports:
    - port: 8800
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    name: apache
  type: LoadBalancer
