kind: Config
clusters:
- name: local
  cluster:
    server: http://172.16.1.2:8080
users:
- name: ubuntu
  user:
    password: p1NVMZqhOOOqkWQq
    username: admin
contexts:
- context:
    cluster: local
    user: ubuntu
  name: ubuntu
current-context: ubuntu
