apiVersion: v1
kind: Service
metadata:
  labels:
    name: apacheservice
    role: service
  name: apacheservice
  namespace: guru
spec:
  ports:
    - port: 8800
      targetPort: 80
      protocol: TCP
      name: tcp
    - port: 8900
      targetPort: 90
      protocol: UDP
      name: udp
  selector:
    name: apache
